services:
  avbot: &avbot
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - db
  celery_worker:
    <<: *avbot
    command: celery -A avbot.tasks worker -l info
  redis:
    image: "redis:alpine"
  db:
    image: postgres:16.1
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
